app = "genmarket-backend"
primary_region = "lhr"

[build]

[env]
  PORT = "4000"
  NODE_ENV = "production"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "genmarket_data"
  destination = "/data"
